### ISSUE TITLE
[问题反馈] [闪避助手] 更新后闪避助手失效

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#102]
### 问题描述

![image](https://github.com/user-attachments/assets/9ba85620-e299-41fe-877b-d390d741d763)
已经启动，但是状态时等待，游戏中无反应

### 问题副本

所有战斗界面都不生效

**Comment by DoctorReid** [comment]
更新代码试试，昨晚最后我还可以用的

**Comment by DabengBa** [comment]
检查下配置里的依赖和模型都下载了.

**Comment by smallmj** [comment]
我都重新删除了文件夹再重新下载安装器，重新安装了一遍，结果还是一样

**Comment by yannychina** [comment]
一样的问题

**Comment by DoctorReid** [comment]
游戏分辨率多少

**Comment by smallmj** [comment]
3840*2160全屏

**Comment by DoctorReid** [comment]
改成16:9的试试

**Comment by DoctorReid** [comment]
我开4k试了下是没问题的，可以用F11在战斗画面里截个图给我看看

**Comment by DoctorReid** [comment]
全屏的话，还需要你的屏幕分辨率也是一样的分辨率，你可以尝试4k的窗口看看

**Comment by smallmj** [comment]
切换到窗口模式依然无法运行，而且不光是闪避助手运行无效，运行自动战斗时提示下面的错误，也无法运行，重新安装依然无法解决。

Traceback (most recent call last):
  File "D:\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\operation_task.py", line 54, in _run
    future.result()
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\atomic_op\btn_common.py", line 99, in execute
    self._method(press=self.is_press, press_time=self.press_time, release=self.is_release)
  File "D:\ZenlessZoneZero-OneDragon\src\zzz_od\context\battle_context.py", line 276, in lock
    self.ctx.controller.lock(press=press, press_time=press_time, release=release)
  File "D:\ZenlessZoneZero-OneDragon\src\zzz_od\controller\zzz_pc_controller.py", line 266, in lock
    self.btn_controller.press(self.key_lock, press_time)
  File "D:\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_button\xbox_button_controller.py", line 168, in press
    self._tab_handler[int(key.split('_')[-1])](press_time)
                          ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by smallmj** [comment]
切换到窗口模式依然无法运行，而且不光是闪避助手运行无效，运行自动战斗时提示下面的错误，也无法运行，重新安装依然无法解决。

Traceback (most recent call last):
  File "D:\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\operation_task.py", line 54, in _run
    future.result()
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\atomic_op\btn_common.py", line 99, in execute
    self._method(press=self.is_press, press_time=self.press_time, release=self.is_release)
  File "D:\ZenlessZoneZero-OneDragon\src\zzz_od\context\battle_context.py", line 276, in lock
    self.ctx.controller.lock(press=press, press_time=press_time, release=release)
  File "D:\ZenlessZoneZero-OneDragon\src\zzz_od\controller\zzz_pc_controller.py", line 266, in lock
    self.btn_controller.press(self.key_lock, press_time)
  File "D:\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_button\xbox_button_controller.py", line 168, in press
    self._tab_handler[int(key.split('_')[-1])](press_time)
                          ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
