### ISSUE TITLE
[问题反馈] [闪避助手] 

### ISSUE THREAD

**Issue by chenxisandy** [DoctorReid/ZenlessZoneZero-OneDragon#123]
### 问题描述

1运行闪避助手直接报错

### 问题副本

任何情况下

### 运行日志

D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\gui\view\battle_assistant\dodge_assistant_interface.py:92: RuntimeWarning: Failed to disconnect (<bound method DodgeAssistantInterface._on_dodge_way_changed of <zzz_od.gui.view.battle_assistant.dodge_assistant_interface.DodgeAssistantInterface(0x25ed988f4b0, name="dodge_assistant_interface") at 0x0000025ED8BB3D40>>) from signal "value_changed(int,PyObject)".
  self.dodge_opt.value_changed.disconnect(self._on_dodge_way_changed)
[23:33:39.759] [operation.py 366] [INFO]: 指令[ 闪避助手 ] 节点 检测游戏窗口 返回状态 成功
[23:33:39.766] [operation.py 366] [INFO]: 指令[ 闪避助手 ] 节点 手柄检测 返回状态 已安装虚拟手柄依赖
[23:33:39.774] [auto_battle_operator.py 278] [INFO]: 松开所有按键
[23:33:39.775] [operation.py 304] [ERROR]: 指令[ 闪避助手 ] 执行出错
Traceback (most recent call last):
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 352, in _execute_one_round
    current_round_result: OperationRoundResult = current_op()
                                                 ^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\dodge_assistant_app.py", line 87, in load_op
    result = auto_battle_utils.load_auto_op(self, 'dodge',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_utils.py", line 24, in load_auto_op
    op.auto_op.init_operator()
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 83, in init_operator
    ConditionalOperator.init(
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\conditional_operator.py", line 61, in init
    self.dispose()  # 先把旧的清除掉
    ^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 267, in dispose
    ConditionalOperator.dispose(self)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\conditional_operator.py", line 92, in dispose
    self.stop_running()  # 在这里强制停止运行
    ^^^^^^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 295, in stop_running
    op.execute()
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\atomic_op\btn_move_w.py", line 24, in execute
    self.ctx.battle.move_w(self.press, self.press_time, self.release)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\context\battle_context.py", line 232, in move_w
    self.ctx.controller.move_w(press=press, press_time=press_time, release=release)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\controller\zzz_pc_controller.py", line 205, in move_w
    self.btn_controller.release(self.key_move_w)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_button\xbox_button_controller.py", line 173, in release
    self.release_handler[int(key.split('_')[-1])]()
                             ^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
[23:33:39.776] [auto_battle_operator.py 278] [INFO]: 松开所有按键
[23:33:39.776] [operation.py 304] [ERROR]: 指令[ 闪避助手 ] 执行出错
Traceback (most recent call last):
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 352, in _execute_one_round
    current_round_result: OperationRoundResult = current_op()
                                                 ^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\dodge_assistant_app.py", line 87, in load_op
    result = auto_battle_utils.load_auto_op(self, 'dodge',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_utils.py", line 19, in load_auto_op
    op.auto_op.dispose()
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 267, in dispose
    ConditionalOperator.dispose(self)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\conditional_operator.py", line 92, in dispose
    self.stop_running()  # 在这里强制停止运行
    ^^^^^^^^^^^^^^^^^^^
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 295, in stop_running
    op.execute()
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\atomic_op\btn_move_w.py", line 24, in execute
    self.ctx.battle.move_w(self.press, self.press_time, self.release)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\context\battle_context.py", line 232, in move_w
    self.ctx.controller.move_w(press=press, press_time=press_time, release=release)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\controller\zzz_pc_controller.py", line 205, in move_w
    self.btn_controller.release(self.key_move_w)
  File "D:\other\Auto_ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_button\xbox_button_controller.py", line 173, in release
    self.release_handler[int(key.split('_')[-1])]()
                             ^^^^^^^^^

**Comment by DoctorReid** [comment]
手柄按键重新设置一下
