### ISSUE TITLE
[问题反馈] [通用] 安装器-一键安装-运行依赖安装失败

### ISSUE THREAD

**Issue by WhiteBlock114514** [DoctorReid/ZenlessZoneZero-OneDragon#208]
### 问题描述

在下载完整包，第一次在从未安装过的电脑上运行安装器时，无法正常安装运行依赖。无论是尝试分步骤运行 git-python环境 的安装，还是采用一键安装，均会报错。直接尝试启动 launcher 会在5s后闪退。

### 运行日志

[15:05:20.211] [git_service.py 289] [INFO]: 获取依赖文件的最后修改时间
[15:05:20.212] [git_service.py 255] [INFO]: 检测当前代码分支
[15:05:20.212] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe -c import sys; print(getattr(sys, 'base_prefix', sys.prefix) != sys.prefix)
[15:05:20.212] [git_service.py 67] [INFO]: 检测当前git版本
[15:05:20.212] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe log -1 --pretty=format:"%ai -- requirements-prod.txt
[15:05:20.213] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe branch --show-current
[15:05:20.216] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe --version
[15:05:20.272] [cmd_utils.py 49] [INFO]: git version 2.45.2.windows.1
[15:05:20.274] [cmd_utils.py 49] [INFO]: True
[15:05:20.275] [cmd_utils.py 49] [INFO]: main
[15:05:20.277] [python_service.py 160] [INFO]: 检测当前python版本
[15:05:20.278] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe --version
[15:05:20.279] [git_service.py 172] [INFO]: 获取远程代码
[15:05:20.280] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe fetch origin main
[15:05:20.284] [cmd_utils.py 49] [INFO]: 2024-08-20 11:00:44 +0800
[15:05:20.302] [cmd_utils.py 49] [INFO]: Python 3.11.9
[15:05:20.933] [cmd_utils.py 57] [ERROR]: From https://github.com/DoctorReid/ZenlessZoneZero-OneDragon
[15:05:20.933] [cmd_utils.py 57] [ERROR]: * branch            main       -> FETCH_HEAD
[15:05:20.934] [git_service.py 180] [ERROR]: 获取远程代码成功
[15:05:20.934] [git_service.py 277] [INFO]: 检测当前代码是否最新
[15:05:20.934] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\PortableGit\cmd\git.exe diff --name-only HEAD origin/main
[15:05:24.455] [cmd_utils.py 19] [INFO]: D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\scripts\python.exe -m pip install --upgrade pip --index-url https://pypi.tuna.tsinghua.edu.cn/simple
[15:05:24.811] [cmd_utils.py 57] [ERROR]: Traceback (most recent call last):
[15:05:24.811] [cmd_utils.py 57] [ERROR]: File "<frozen runpy>", line 198, in _run_module_as_main
[15:05:24.811] [cmd_utils.py 57] [ERROR]: File "<frozen runpy>", line 88, in _run_code
[15:05:24.813] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\__main__.py", line 24, in <module>
[15:05:24.814] [cmd_utils.py 57] [ERROR]: sys.exit(_main())
[15:05:24.814] [cmd_utils.py 57] [ERROR]: ^^^^^^^
[15:05:24.814] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main.py", line 65, in main
[15:05:24.816] [cmd_utils.py 57] [ERROR]: cmd_name, cmd_args = parse_command(args)
[15:05:24.816] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^
[15:05:24.816] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 79, in parse_command
[15:05:24.817] [cmd_utils.py 57] [ERROR]: general_options, args_else = parser.parse_args(args)
[15:05:24.817] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.818] [cmd_utils.py 57] [ERROR]: File "optparse.py", line 1371, in parse_args
[15:05:24.818] [cmd_utils.py 57] [ERROR]: values = self.get_default_values()
[15:05:24.818] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.818] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\parser.py", line 279, in get_default_values
[15:05:24.819] [cmd_utils.py 57] [ERROR]: self.config.load()
[15:05:24.819] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 124, in load
[15:05:24.820] [cmd_utils.py 57] [ERROR]: self._load_config_files()
[15:05:24.820] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 246, in _load_config_files
[15:05:24.820] [cmd_utils.py 57] [ERROR]: config_files = dict(self.iter_config_files())
[15:05:24.821] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.821] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 339, in iter_config_files
[15:05:24.822] [cmd_utils.py 57] [ERROR]: config_files = get_configuration_files()
[15:05:24.822] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.823] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 70, in get_configuration_files
[15:05:24.823] [cmd_utils.py 57] [ERROR]: os.path.join(path, CONFIG_BASENAME) for path in appdirs.site_config_dirs("pip")
[15:05:24.824] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.824] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 47, in site_config_dirs
[15:05:24.824] [cmd_utils.py 57] [ERROR]: dirval = _appdirs.site_config_dir(appname, appauthor=False, multipath=True)
[15:05:24.824] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.826] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 142, in site_config_dir
[15:05:24.826] [cmd_utils.py 57] [ERROR]: ).site_config_dir
[15:05:24.826] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^
[15:05:24.827] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 67, in site_config_dir
[15:05:24.827] [cmd_utils.py 57] [ERROR]: return self.site_data_dir
[15:05:24.828] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^
[15:05:24.829] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 56, in site_data_dir
[15:05:24.829] [cmd_utils.py 57] [ERROR]: path = os.path.normpath(get_win_folder("CSIDL_COMMON_APPDATA"))
[15:05:24.830] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.830] [cmd_utils.py 57] [ERROR]: File "D:\MyPrograms\Tools\ZenlessZoneZero-OneDragon-1.1.4\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 209, in get_win_folder_from_registry
[15:05:24.831] [cmd_utils.py 57] [ERROR]: directory, _ = winreg.QueryValueEx(key, shell_folder_name)
[15:05:24.834] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[15:05:24.836] [cmd_utils.py 57] [ERROR]: FileNotFoundError: [WinError 2] The system cannot find the file specified

### 你的建议

推测为境外无法正常访问清华镜像源pip导致。请给予境外用户选择官方源的选项。

**Comment by DoctorReid** [comment]
可先自行修改 project.yml line 11
```yml
pip_source: "https://pypi.tuna.tsinghua.edu.cn/simple"
```
