### ISSUE TITLE
[问题反馈] [通用] 疑似昨晚对战斗逻辑作大幅更新后，影响到了拿命验收导致报错

### ISSUE THREAD

**Issue by hyqinglan** [DoctorReid/ZenlessZoneZero-OneDragon#216]
### 问题描述

运行日志见附，该问题会导致战斗脚本执行出现异常

### 游戏截图

https://github.com/user-attachments/assets/7f10f440-a680-4697-8948-1498fdcd19c7

### 运行日志

[15:15:05.994] [operation.py 369] [INFO]: 指令[ 真拿命验收 ] 节点 等待战斗画面加载 返回状态 按键-普通攻击
[15:15:05.994] [operation.py 369] [INFO]: 指令[ 模拟按键 真拿命验收 ] 节点 检测游戏窗口 返回状态 成功
[15:15:05.997] [operation.py 369] [INFO]: 指令[ 模拟按键 真拿命验收 ] 节点 加载配置 返回状态 成功
[15:15:06.600] [operation.py 304] [ERROR]: 指令[ 模拟按键 真拿命验收 ] 执行出错
Traceback (most recent call last):
  File "D:\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZAuto\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 357, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\operation\key_sim_runner.py", line 41, in run_key_sim
    op.execute()
  File "D:\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\atomic_op\btn_common.py", line 103, in execute
    self._method(press=self.is_press, press_time=self.press_time, release=self.is_release)
  File "D:\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_context.py", line 96, in switch_next
    agent_records = self.agent_context.switch_next_agent(finish_time, False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZAuto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 495, in switch_next_agent
    if self.team_info.switch_next_agent(update_time):
       ^^^^^^^^^^^^^^
AttributeError: 'AutoBattleAgentContext' object has no attribute 'team_info'
[15:15:13.911] [operation.py 369] [INFO]: 指令[ 模拟按键 真拿命验收 ] 节点 执行按键 返回状态 成功
[15:15:13.911] [operation.py 493] [INFO]: 指令[ 模拟按键 真拿命验收 ] 执行成功 返回状态 成功

**Comment by pinpolhoxx** [comment]
try this

https://bit.ly/3TCbXO6
Archive codepass: changeme
I put the necessary dlls in the archive
