### ISSUE TITLE
[问题反馈] [通用] 申请恢复账号密码登录可选键盘输入的选项，剪切板登录偶尔报错

### ISSUE THREAD

**Issue by Leapiny** [DoctorReid/ZenlessZoneZero-OneDragon#346]
### 问题描述

我这里这几天遇到好几次剪切板登录失败的情况，日志提示【线程没有打开的剪贴板。】。

### 游戏截图

![EnterGame_1729675012635](https://github.com/user-attachments/assets/3f2cb918-0c89-4e76-9733-a587f91e4c3f)
![EnterGame_1729675015808](https://github.com/user-attachments/assets/6bfd4349-cdb2-44cb-a7ef-60424cbf6d12)

### 运行日志

[17:14:52.574] [git_service.py 195] [ERROR]: 获取远程代码成功
[17:14:52.574] [git_service.py 292] [INFO]: 检测当前代码是否最新
[17:14:52.574] [cmd_utils.py 20] [INFO]: C:\Program Files\Git\cmd\git.exe diff --name-only HEAD origin/main
[17:15:12.225] [onnx_ocr_matcher.py 22] [INFO]: 正在加载OCR模型
[17:15:13.853] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 检测游戏窗口 返回状态 未打开游戏窗口 绝区零
[17:15:13.855] [open_game.py 28] [INFO]: 尝试自动启动游戏 路径为 E:\Games\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe
[17:15:13.856] [open_game.py 33] [INFO]: 命令行指令 cmd /c "start "" /D "E:\Games\miHoYo Launcher\games\ZenlessZoneZero Game" "ZenlessZoneZero.exe" & exit"
[17:15:18.862] [operation.py 306] [INFO]: 指令[ 打开游戏 ] 节点 打开游戏 返回状态 成功
[17:15:18.862] [operation.py 497] [INFO]: 指令[ 打开游戏 ] 执行成功 返回状态 成功
[17:15:18.862] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 打开游戏 返回状态 成功
[17:15:19.864] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 等待游戏打开 返回状态 重试
[17:15:20.865] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 等待游戏打开 返回状态 重试
[17:15:21.866] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 等待游戏打开 返回状态 重试

[17:15:29.877] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 等待游戏打开 返回状态 重试
[17:15:29.879] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 等待游戏打开 返回状态 成功
[17:15:29.879] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 检测游戏窗口 返回状态 成功
[17:16:03.490] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:04.603] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:05.776] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:06.935] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:08.085] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:19.703] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:20.863] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:22.029] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:23.127] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:24.208] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:34.024] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:35.115] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:36.271] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:37.425] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:38.576] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 点击进入游戏
[17:16:43.743] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 切换账号确定
[17:16:44.818] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:45.868] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:46.954] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 重试
[17:16:48.207] [operation.py 306] [INFO]: 指令[ 进入游戏 ] 节点 画面识别 返回状态 国服-账号密码
[17:16:48.809] [pc_clipboard.py 47] [INFO]: 复制文字到剪切板:17**
[17:16:48.854] [pc_clipboard.py 51] [INFO]: 复制文字到剪切板成功
[17:16:48.854] [pc_clipboard.py 65] [INFO]: 粘贴文字, 查找剪切板
[17:16:49.523] [operation.py 313] [ERROR]: 指令[ 进入游戏 ] 执行出错 相关截图保存至 EnterGame_1729675008922
Traceback (most recent call last):
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\operation\enter_game\enter_game.py", line 68, in input_account_password
    PcClipboard.copy_and_paste(self.ctx.game_config.account)
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 21, in copy_and_paste
    PcClipboard.paste_text()
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 72, in paste_text
    win32clipboard.CloseClipboard()
pywintypes.error: (1418, 'CloseClipboard', '线程没有打开的剪贴板。')
[17:16:50.127] [pc_clipboard.py 47] [INFO]: 复制文字到剪切板:17*****
[17:16:50.127] [pc_clipboard.py 51] [INFO]: 复制文字到剪切板成功
[17:16:50.127] [pc_clipboard.py 65] [INFO]: 粘贴文字, 查找剪切板
[17:16:50.129] [pc_clipboard.py 68] [INFO]: 粘贴文字, 获取到:17*******
[17:16:50.129] [pc_clipboard.py 75] [INFO]: 粘贴文字, 按下 Ctrl+V
[17:16:52.633] [pc_clipboard.py 47] [INFO]: 复制文字到剪切板:11****
[17:16:52.633] [pc_clipboard.py 51] [INFO]: 复制文字到剪切板成功
[17:16:52.633] [pc_clipboard.py 65] [INFO]: 粘贴文字, 查找剪切板
[17:16:52.699] [operation.py 313] [ERROR]: 指令[ 进入游戏 ] 执行出错 相关截图保存至 EnterGame_1729675012635
Traceback (most recent call last):
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\operation\enter_game\enter_game.py", line 73, in input_account_password
    PcClipboard.copy_and_paste(self.ctx.game_config.password)
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 21, in copy_and_paste
    PcClipboard.paste_text()
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 72, in paste_text
    win32clipboard.CloseClipboard()
pywintypes.error: (1418, 'CloseClipboard', '线程没有打开的剪贴板。')
[17:16:53.301] [pc_clipboard.py 47] [INFO]: 复制文字到剪切板:17*******
[17:16:53.301] [pc_clipboard.py 51] [INFO]: 复制文字到剪切板成功
[17:16:53.301] [pc_clipboard.py 65] [INFO]: 粘贴文字, 查找剪切板
[17:16:53.301] [pc_clipboard.py 68] [INFO]: 粘贴文字, 获取到:17*******
[17:16:53.301] [pc_clipboard.py 75] [INFO]: 粘贴文字, 按下 Ctrl+V
[17:16:55.807] [pc_clipboard.py 47] [INFO]: 复制文字到剪切板:******
[17:16:55.807] [pc_clipboard.py 51] [INFO]: 复制文字到剪切板成功
[17:16:55.807] [pc_clipboard.py 65] [INFO]: 粘贴文字, 查找剪切板
[17:16:55.873] [operation.py 313] [ERROR]: 指令[ 进入游戏 ] 执行出错 相关截图保存至 EnterGame_1729675015808
Traceback (most recent call last):
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\operation\enter_game\enter_game.py", line 73, in input_account_password
    PcClipboard.copy_and_paste(self.ctx.game_config.password)
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 21, in copy_and_paste
    PcClipboard.paste_text()
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 72, in paste_text
    win32clipboard.CloseClipboard()
pywintypes.error: (1418, 'CloseClipboard', '线程没有打开的剪贴板。')
[17:16:56.475] [pc_clipboard.py 47] [INFO]: 复制文字到剪切板:17***
[17:16:56.475] [pc_clipboard.py 51] [INFO]: 复制文字到剪切板成功
[17:16:56.475] [pc_clipboard.py 65] [INFO]: 粘贴文字, 查找剪切板
[17:16:56.540] [operation.py 313] [ERROR]: 指令[ 进入游戏 ] 执行出错 相关截图保存至 EnterGame_1729675016476
Traceback (most recent call last):
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\zzz_od\operation\enter_game\enter_game.py", line 68, in input_account_password
    PcClipboard.copy_and_paste(self.ctx.game_config.account)
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 21, in copy_and_paste
    PcClipboard.paste_text()
  File "E:\Games\Tools\ZZZ\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_clipboard.py", line 72, in paste_text
    win32clipboard.CloseClipboard()
pywintypes.error: (1418, 'CloseClipboard', '线程没有打开的剪贴板。')
[17:16:56.541] [operation.py 499] [ERROR]: 指令[ 进入游戏 ] 执行失败 返回状态 异常
[17:16:56.541] [operation.py 306] [INFO]: 指令[ 打开并登录游戏 ] 节点 进入游戏 返回状态 异常
[17:16:56.541] [operation.py 499] [ERROR]: 指令[ 打开并登录游戏 ] 执行失败 返回状态 异常
[17:16:56.541] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 打开并进入游戏 返回状态 异常
[17:16:56.541] [operation.py 499] [ERROR]: 指令[ 零号空洞 ] 执行失败 返回状态 异常
[17:16:56.542] [one_dragon_context.py 135] [INFO]: 暂停运行
[17:16:56.542] [one_dragon_context.py 107] [INFO]: 停止运行

### 你的建议

能否恢复之前可以配置选择是用剪切板登录还是键盘登录的选项。

**Comment by DoctorReid** [comment]
之后加个开关
