### ISSUE TITLE
[问题反馈] [通用] 自动战斗失效

### ISSUE THREAD

**Issue by DeeJay0921** [DoctorReid/ZenlessZoneZero-OneDragon#361]
### 问题描述

可以正常进入所选择副本，且可以正常向前移动，但移动之后并不会自动战斗，使用自动战斗进行调试报错，信息如下：
指令[ 自动战斗调试 ] 执行出错 相关截图保存至 AutoBattleDebugApp_1730076171830 Traceback (most recent call last): File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_debug_app.py", line 93, in check_screen ops = self.auto_op._normal_scene_handler.get_operations(time.time()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'get_operations'

### 运行日志

[08:42:50.573] [onnx_model_loader.py 124] [INFO]: 加载模型 F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\assets\models\flash_classifier\yolov8n-640-flash-0718\model.onnx
[08:42:50.715] [operation.py 306] [INFO]: 指令[ 自动战斗调试 ] 节点 加载自动战斗指令 返回状态 成功
[08:42:50.715] [auto_battle_dodge_context.py 184] [INFO]: 加载声音模板中
[08:42:50.727] [auto_battle_dodge_context.py 192] [INFO]: 加载声音模板完成
[08:42:51.094] [operation.py 313] [ERROR]: 指令[ 自动战斗调试 ] 执行出错 相关截图保存至 AutoBattleDebugApp_1730076171091
Traceback (most recent call last):
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_debug_app.py", line 93, in check_screen
    ops = self.auto_op._normal_scene_handler.get_operations(time.time())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_operations'
[08:42:51.467] [operation.py 313] [ERROR]: 指令[ 自动战斗调试 ] 执行出错 相关截图保存至 AutoBattleDebugApp_1730076171466
Traceback (most recent call last):
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_debug_app.py", line 93, in check_screen
    ops = self.auto_op._normal_scene_handler.get_operations(time.time())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_operations'
[08:42:51.832] [operation.py 313] [ERROR]: 指令[ 自动战斗调试 ] 执行出错 相关截图保存至 AutoBattleDebugApp_1730076171830
Traceback (most recent call last):
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_debug_app.py", line 93, in check_screen
    ops = self.auto_op._normal_scene_handler.get_operations(time.time())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_operations'
[08:42:52.190] [operation.py 313] [ERROR]: 指令[ 自动战斗调试 ] 执行出错 相关截图保存至 AutoBattleDebugApp_1730076172188
Traceback (most recent call last):
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\MiHoYo\Scripts\ZenlessZoneZero-OneDragon\src\zzz_od\application\battle_assistant\auto_battle_debug_app.py", line 93, in check_screen
    ops = self.auto_op._normal_scene_handler.get_operations(time.time())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_operations'
[08:42:52.192] [operation.py 499] [ERROR]: 指令[ 自动战斗调试 ] 执行失败 返回状态 异常

**Comment by DeeJay0921** [comment]
排查问题为安装了更改角色icon的mod，导致识别出错
