### ISSUE TITLE
[问题反馈] [零号空洞] 零号空洞脚本运行报错

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/ZenlessZoneZero-OneDragon#381]
### 问题描述

选人界面一结束就报错退出，之前好好的，设置都没改过，这周一运行就不行了

log：

[08:22:38.814] [onnx_ocr_matcher.py 25] [INFO]: 正在加载OCR模型
[08:22:38.818] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 检测游戏窗口 返回状态 成功
[08:22:39.304] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 初始画面识别 返回状态 信息
[08:22:39.304] [operation.py 306] [INFO]: 指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 检测游戏窗口 返回状态 成功
[08:22:39.305] [operation.py 306] [INFO]: 指令[ 打开快捷手册 ] 节点 检测游戏窗口 返回状态 成功
[08:22:39.305] [operation.py 306] [INFO]: 指令[ 打开菜单 ] 节点 检测游戏窗口 返回状态 成功
[08:22:39.363] [operation.py 306] [INFO]: 指令[ 打开菜单 ] 节点 画面识别 返回状态 信息
[08:22:41.673] [operation.py 306] [INFO]: 指令[ 打开菜单 ] 节点 点击菜单 返回状态 成功
[08:22:42.060] [operation.py 306] [INFO]: 指令[ 打开菜单 ] 节点 画面识别 返回状态 成功
[08:22:42.060] [operation.py 497] [INFO]: 指令[ 打开菜单 ] 执行成功 返回状态 成功
[08:22:42.061] [operation.py 306] [INFO]: 指令[ 打开快捷手册 ] 节点 打开菜单 返回状态 成功
[08:22:43.575] [operation.py 306] [INFO]: 指令[ 打开快捷手册 ] 节点 点击更多 返回状态 快捷手册
[08:22:43.575] [operation.py 497] [INFO]: 指令[ 打开快捷手册 ] 执行成功 返回状态 快捷手册
[08:22:43.575] [operation.py 306] [INFO]: 指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 快捷手册 返回状态 快捷手册
[08:22:43.576] [operation.py 306] [INFO]: 指令[ 快捷手册 选择Tab 挑战 ] 节点 检测游戏窗口 返回状态 成功
[08:22:44.818] [operation.py 306] [INFO]: 指令[ 快捷手册 选择Tab 挑战 ] 节点 选择TAB 返回状态 成功
[08:22:44.819] [operation.py 497] [INFO]: 指令[ 快捷手册 选择Tab 挑战 ] 执行成功 返回状态 成功
[08:22:44.819] [operation.py 306] [INFO]: 指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 选择TAB 返回状态 成功
[08:22:44.819] [operation.py 306] [INFO]: 指令[ 快捷手册 选择分类 零号空洞 ] 节点 检测游戏窗口 返回状态 成功
[08:22:46.070] [operation.py 306] [INFO]: 指令[ 快捷手册 选择分类 零号空洞 ] 节点 选择分类 返回状态 成功
[08:22:46.070] [operation.py 497] [INFO]: 指令[ 快捷手册 选择分类 零号空洞 ] 执行成功 返回状态 成功
[08:22:46.070] [operation.py 306] [INFO]: 指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 选择分类 返回状态 成功
[08:22:46.071] [operation.py 306] [INFO]: 指令[ 快捷手册 选择副本类型 资质考核 ] 节点 检测游戏窗口 返回状态 成功
[08:22:47.490] [operation.py 306] [INFO]: 指令[ 快捷手册 选择副本类型 资质考核 ] 节点 选择副本 返回状态 成功
[08:22:52.673] [operation.py 306] [INFO]: 指令[ 快捷手册 选择副本类型 资质考核 ] 节点 确认 返回状态 传送确认
[08:22:52.673] [operation.py 497] [INFO]: 指令[ 快捷手册 选择副本类型 资质考核 ] 执行成功 返回状态 传送确认
[08:22:52.673] [operation.py 306] [INFO]: 指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 节点 选择副本分类 返回状态 传送确认
[08:22:52.673] [operation.py 497] [INFO]: 指令[ 传送 快捷手册 挑战-零号空洞-资质考核 ] 执行成功 返回状态 传送确认
[08:22:52.673] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 传送 返回状态 传送确认
[08:22:52.719] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 等待入口加载 返回状态 街区
[08:22:54.160] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 选择副本类型 返回状态 旧都列车
[08:22:55.421] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 选择副本 返回状态 旧都列车-核心
[08:22:56.670] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 下一步 返回状态 下一步
[08:22:57.760] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 下一步 返回状态 出战
[08:22:57.760] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 检测游戏窗口 返回状态 成功
[08:22:58.906] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 出战 返回状态 出战
[08:22:59.935] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
[08:23:00.970] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
[08:23:02.009] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
[08:23:03.041] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 识别低等级 返回状态 未找到 确定并出战
[08:23:03.041] [operation.py 306] [INFO]: 指令[ 出战 ] 节点 进入成功 返回状态 成功
[08:23:03.041] [operation.py 497] [INFO]: 指令[ 出战 ] 执行成功 返回状态 成功
[08:23:03.041] [operation.py 306] [INFO]: 指令[ 零号空洞 ] 节点 出战 返回状态 成功
[08:23:05.129] [operation.py 313] [ERROR]: 指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1730679785093
Traceback (most recent call last):
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 146, in auto_run
    self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start
    self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo
    self._event_model = HollowEventDetector(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__
    Yolov8Detector.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__
    OnnxModelLoader.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__
    self.load_model()
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model
    self.session = ort.InferenceSession(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed:Load model C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed. File doesn't exist
[08:23:07.212] [operation.py 313] [ERROR]: 指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1730679787181
Traceback (most recent call last):
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 146, in auto_run
    self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start
    self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo
    self._event_model = HollowEventDetector(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__
    Yolov8Detector.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__
    OnnxModelLoader.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__
    self.load_model()
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model
    self.session = ort.InferenceSession(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed:Load model C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed. File doesn't exist
[08:23:09.303] [operation.py 313] [ERROR]: 指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1730679789268
Traceback (most recent call last):
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 146, in auto_run
    self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start
    self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo
    self._event_model = HollowEventDetector(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__
    Yolov8Detector.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__
    OnnxModelLoader.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__
    self.load_model()
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model
    self.session = ort.InferenceSession(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed:Load model C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed. File doesn't exist
[08:23:11.395] [operation.py 313] [ERROR]: 指令[ 零号空洞 ] 执行出错 相关截图保存至 HollowZeroApp_1730679791361
Traceback (most recent call last):
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute
    round_result: OperationRoundResult = self._execute_one_round()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round
    current_round_result: OperationRoundResult = self._current_node.op_method(self)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\application\hollow_zero\hollow_zero_app.py", line 146, in auto_run
    self.ctx.hollow.init_before_hollow_start(self.mission_type_name, self.mission_name, self.level, self.phase)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 444, in init_before_hollow_start
    self.ctx.hollow.init_event_yolo(self.ctx.yolo_config.hollow_zero_event_gpu)
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\context\hollow_context.py", line 64, in init_event_yolo
    self._event_model = HollowEventDetector(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\zzz_od\yolo\hollow_event_detector.py", line 25, in __init__
    Yolov8Detector.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\yolov8_onnx_det.py", line 35, in __init__
    OnnxModelLoader.__init__(
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 39, in __init__
    self.load_model()
  File "C:\zzz\ZenlessZoneZero-OneDragon\src\one_dragon\yolo\onnx_model_loader.py", line 126, in load_model
    self.session = ort.InferenceSession(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\zzz\ZenlessZoneZero-OneDragon\.env\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed:Load model C:\zzz\ZenlessZoneZero-OneDragon\assets\models\hollow_zero_event\yolov8s-736-hollow-zero-event-1027\model.onnx failed. File doesn't exist
[08:23:11.396] [operation.py 499] [ERROR]: 指令[ 零号空洞 ] 执行失败 返回状态 异常
[08:23:11.396] [one_dragon_context.py 135] [INFO]: 暂停运行
[08:23:11.396] [one_dragon_context.py 107] [INFO]: 停止运行
[08:23:11.406] [pc_controller_base.py 190] [INFO]: 关闭游戏成功
[08:23:11.411] [pc_controller_base.py 190] [INFO]: 关闭游戏成功

### 问题副本

零号空洞

### 游戏截图/录屏

![HollowZeroApp_1730679789268](https://github.com/user-attachments/assets/63637b7a-398c-4f46-9adc-704d48e45810)

**Comment by yokuminto** [comment]
看起来像模型异常，重装下试试
