### ISSUE TITLE
[问题反馈] [通用] 多实例设置关闭游戏，一条龙完成后，没有关闭游戏

### ISSUE THREAD

**Issue by SuperSB** [DoctorReid/ZenlessZoneZero-OneDragon#396]
### 问题描述

多实例设置关闭游戏，一条龙完成后，没有关闭游戏

### 运行日志

[log.txt](https://github.com/user-attachments/files/17670797/log.txt)

**Comment by meiszzz** [comment]
同样的问题，没有使用多账号，仅使用默认的账号01
我的游戏路径D:\ZenlessZoneZero Game\ZenlessZoneZero.exe

[17:27:39.052] [operation.py 499] [ERROR]: 指令[ 每周行程 ] 执行失败 返回状态 未找到 行程安排
[17:27:39.053] [operation.py 306] [INFO]: 指令[ 一条龙 ] 节点 重试失败任务 返回状态 下一个
[17:27:39.053] [operation.py 306] [INFO]: 指令[ 一条龙 ] 节点 重试失败任务 返回状态 全部结束
[17:27:39.054] [one_dragon_context.py 206] [INFO]: 开始加载实例配置 1
[17:27:39.125] [one_dragon_app.py 161] [INFO]: 下一个实例 账号01
[17:27:39.126] [operation.py 306] [INFO]: 指令[ 一条龙 ] 节点 切换实例配置 返回状态 成功
[17:27:39.126] [operation.py 306] [INFO]: 指令[ 一条龙 ] 节点 切换账号 返回状态 无需切换账号
[17:27:39.126] [operation.py 306] [INFO]: 指令[ 一条龙 ] 节点 切换账号后处理 返回状态 全部结束
[17:27:39.126] [operation.py 497] [INFO]: 指令[ 一条龙 ] 执行成功 返回状态 全部结束
[17:27:39.127] [one_dragon_context.py 135] [INFO]: 暂停运行
[17:27:39.127] [one_dragon_context.py 107] [INFO]: 停止运行
[17:27:39.141] [pc_controller_base.py 192] [ERROR]: 关闭游戏失败
Traceback (most recent call last):
  File "D:\cy\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_controller_base.py", line 189, in close_game
    self.game_win.win.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'PcGameWindow' object has no attribute 'win'
[17:27:39.146] [pc_controller_base.py 192] [ERROR]: 关闭游戏失败
Traceback (most recent call last):
  File "D:\cy\ZenlessZoneZero-OneDragon\src\one_dragon\base\controller\pc_controller_base.py", line 189, in close_game
    self.game_win.win.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'PcGameWindow' object has no attribute 'win'
