### ISSUE TITLE
[问题反馈] [通用] 疑似不兼容win11 24H2

### ISSUE THREAD

**Issue by lycm02** [DoctorReid/ZenlessZoneZero-OneDragon#488]
### 代码版本

000000

### 问题描述

更新Win11 24H2版本后，打开软件出现文字不显示和窗口变形，尝试重新安装后无变化

### 游戏截图

![屏幕截图 2024-12-11 160659](https://github.com/user-attachments/assets/96003532-3235-4715-8c2e-835115032083)

### 运行日志

[15:58:04.192] [git_service.py 270] [INFO]: 检测当前代码分支
[15:58:04.192] [cmd_utils.py 20] [INFO]:  branch --show-current
[15:58:04.195] [git_service.py 304] [INFO]: 获取依赖文件的最后修改时间
[15:58:04.198] [cmd_utils.py 76] [ERROR]: 执行命令失败
Traceback (most recent call last):
  File "one_dragon\utils\cmd_utils.py", line 34, in run_command
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
OSError: [WinError 87] 参数错误。
[15:58:04.198] [cmd_utils.py 20] [INFO]:  log -1 --pretty=format:"%ai -- requirements-prod.txt
[15:58:04.203] [cmd_utils.py 76] [ERROR]: 执行命令失败
Traceback (most recent call last):
  File "one_dragon\utils\cmd_utils.py", line 34, in run_command
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
OSError: [WinError 87] 参数错误。
[15:58:47.785] [gamepad_install_card.py 59] [INFO]: 获取依赖文件的最后修改时间
[15:58:47.785] [cmd_utils.py 20] [INFO]:  log -1 --pretty=format:"%ai -- D:\ZenlessZoneZero-OneDragon\requirements-gamepad.txt
[15:58:47.786] [cmd_utils.py 76] [ERROR]: 执行命令失败
Traceback (most recent call last):
  File "one_dragon\utils\cmd_utils.py", line 34, in run_command
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
OSError: [WinError 87] 参数错误。

**Comment by YCR160** [comment]
![](https://github.com/user-attachments/assets/4c3a6ce3-7cd6-4af3-a659-d8fa2d007119)

**Comment by DoctorReid** [comment]
这种系统问题不在能力范围内

- 可以尝试重装系统
- 可以gpt一下如何使用anaconda安装python环境来跳过安装器
