### ISSUE TITLE
[问题反馈] [通用] 模板生成beta点击f9没有反应，请问现在是不能用了吗（

### ISSUE THREAD

**Issue by Dyachi** [DoctorReid/ZenlessZoneZero-OneDragon#501]
### 代码版本

982cb9f

### 问题描述

1.界面切入模板生成beta
2.绝区零进入战斗界面
3.点击F9

### 运行日志

无，完成一局之后没有记录

**Comment by Paper-white** [comment]
补个日志
```
[20:32:33.980] [onnx_ocr_matcher.py 28] [INFO]: 正在加载OCR模型
[20:32:33.981] [onnx_ocr_matcher.py 55] [INFO]: 加载OCR模型完毕
[20:32:34.085] [auto_battle_dodge_context.py 184] [INFO]: 加载声音模板中
[20:32:34.091] [auto_battle_dodge_context.py 192] [INFO]: 加载声音模板完成
[20:32:34.099] [thread_utils.py 10] [ERROR]: 异步执行失败
Traceback (most recent call last):
  File "D:\ZZZ\src\one_dragon\utils\thread_utils.py", line 8, in handle_future_result
    future.result()
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\ZZZ\src\zzz_od\gui\view\battle_assistant\template_generation_interface.py", line 167, in _on_key_press
    self._on_start_clicked()
  File "D:\ZZZ\src\zzz_od\gui\view\battle_assistant\template_generation_interface.py", line 177, in _on_start_clicked
    AppRunInterface._on_start_clicked(self)
  File "D:\ZZZ\src\one_dragon\gui\view\app_run_interface.py", line 186, in _on_start_clicked
    self.run_app()
  File "D:\ZZZ\src\one_dragon\gui\view\app_run_interface.py", line 149, in run_app
    if app.run_record is not None:
       ^^^^^^^^^^^^^^
AttributeError: 'RecordContext' object has no attribute 'run_record'
[20:32:36.085] [auto_battle_context.py 767] [INFO]: 松开所有按键
[20:32:36.089] [one_dragon_context.py 109] [INFO]: 停止运行
```

**Comment by DoctorReid** [comment]
做这个的大佬的确没维护了，有空再看看

**Comment by Dyachi** [comment]
> 做这个的大佬的确没维护了，有空再看看

谢谢！打扰了
