### ISSUE TITLE
[问题反馈] [通用] 

### ISSUE THREAD

**Issue by WSLSealeaf** [DoctorReid/ZenlessZoneZero-OneDragon#543]
### 代码版本

bcb2e26

### 问题描述

自动战斗初始化失败

### 运行日志

[19:39:12.777] [auto_battle_operator.py 88] [ERROR]: 自动战斗初始化失败 共享配队文件请在群内提醒对应作者修复
Traceback (most recent call last):
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 69, in init_before_running
    success, msg = self._init_operator()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_operator.py", line 137, in _init_operator
    op_getter=self.get_atomic_op,
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\conditional_operator.py", line 67, in init
    handler = construct_scene_handler(scene_data, self.get_state_recorder,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 22, in construct_scene_handler
    state_handlers = _get_state_handlers(
                     ^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 76, in _get_state_handlers
    template_state_handlers = _get_state_handlers_by_template(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 54, in _get_state_handlers_by_template
    state_handlers = _get_state_handlers(
                     ^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 83, in _get_state_handlers
    state_handlers.append(construct_state_handler(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 126, in construct_state_handler
    sub_handler_list: List[StateHandler] = _get_state_handlers(
                                           ^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 83, in _get_state_handlers
    state_handlers.append(construct_state_handler(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\utils.py", line 112, in construct_state_handler
    state_cal_tree = construct_state_cal_tree(states_expr, state_getter)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZZZOneDragon\ZenlessZoneZero-OneDragon\src\one_dragon\base\conditional_operation\state_cal_tree.py", line 209, in construct_state_cal_tree
    raise ValueError('位置 %d 的左中括号 后方状态不合法 %s' % (display_idx, state_name))
ValueError: 位置 2 的左中括号 后方状态不合法 妮可-特殊技可用
[19:39:12.779] [operation.py 306] [INFO]: 指令[ 自动战斗 ] 节点 加载自动战斗指令 返回状态 初始化失败
[19:39:12.779] [operation.py 499] [ERROR]: 指令[ 自动战斗 ] 执行失败 返回状态 初始化失败

**Comment by Paper-white** [comment]
![image](https://github.com/user-attachments/assets/e3ff032d-8dca-49b1-bd63-29b00e6f4ea3)

请确保你使用的是基于新版本的战斗配队

**Comment by DoctorReid** [comment]
更新代码后重启脚本
