### ISSUE TITLE
[问题反馈] [通用] 迷失問題紀錄

### ISSUE THREAD

**Issue by 123hi123** [DoctorReid/ZenlessZoneZero-OneDragon#583]
### 代码版本

1a5126d

### 问题描述

![image](https://github.com/user-attachments/assets/dc2b538a-470f-4032-8aff-ea29864b161b)

### 运行日志

[15:09:15.535] [auto_battle_agent_context.py 470] [ERROR]: 识别角色状态失败
Traceback (most recent call last):
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 466, in _check_agent_state_in_parallel
    record = future.result()
             ^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 485, in _check_agent_state
    value = check_method(ctx=self.ctx, screen=screen, state_def=state, total=to_check.total, pos=to_check.pos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\agent_state\agent_state_checker.py", line 186, in check_length_by_foreground_gray
    return int(fg_cnt * state_def.max_length / total_cnt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
[15:09:15.661] [auto_battle_agent_context.py 470] [ERROR]: 识别角色状态失败
Traceback (most recent call last):
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 466, in _check_agent_state_in_parallel
    record = future.result()
             ^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 485, in _check_agent_state
    value = check_method(ctx=self.ctx, screen=screen, state_def=state, total=to_check.total, pos=to_check.pos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\agent_state\agent_state_checker.py", line 186, in check_length_by_foreground_gray
    return int(fg_cnt * state_def.max_length / total_cnt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
[15:09:15.826] [auto_battle_agent_context.py 470] [ERROR]: 识别角色状态失败
Traceback (most recent call last):
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 466, in _check_agent_state_in_parallel
    record = future.result()
             ^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 485, in _check_agent_state
    value = check_method(ctx=self.ctx, screen=screen, state_def=state, total=to_check.total, pos=to_check.pos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\agent_state\agent_state_checker.py", line 186, in check_length_by_foreground_gray
    return int(fg_cnt * state_def.max_length / total_cnt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
[15:09:15.970] [auto_battle_agent_context.py 470] [ERROR]: 识别角色状态失败
Traceback (most recent call last):
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 466, in _check_agent_state_in_parallel
    record = future.result()
             ^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\auto_battle_agent_context.py", line 485, in _check_agent_state
    value = check_method(ctx=self.ctx, screen=screen, state_def=state, total=to_check.total, pos=to_check.pos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\tool\zzz_auto\ZenlessZoneZero-OneDragon\src\zzz_od\auto_battle\agent_state\agent_state_checker.py", line 186, in check_length_by_foreground_gray
    return int(fg_cnt * state_def.max_length / total_cnt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer

**Comment by DoctorReid** [comment]
缺少重现方式无能为力
