### ISSUE TITLE
[问题反馈] [通用] 一条龙启动失败

### ISSUE THREAD

**Issue by MurphyZX** [DoctorReid/ZenlessZoneZero-OneDragon#60]
### 问题描述

![image](https://github.com/user-attachments/assets/d7500236-3ae7-457c-9766-9e5d12552b7b)

### 运行日志

[07:41:54.979] [onnx_ocr_matcher.py 24] [INFO]: 正在加载OCR模型
[07:41:55.041] [operation.py 273] [ERROR]: 初始化失败
Traceback (most recent call last):
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\operation.py", line 271, in execute
    self._init_before_execute()
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\application_base.py", line 60, in _init_before_execute
    self.init_for_application()
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\one_dragon\base\operation\application_base.py", line 119, in init_for_application
    self.ctx.ocr.init_model()
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\one_dragon\base\matcher\ocr\onnx_ocr_matcher.py", line 27, in init_model
    from onnxocr.onnx_paddleocr import ONNXPaddleOcr
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\onnxocr\onnx_paddleocr.py", line 3, in <module>
    from onnxocr.predict_system import TextSystem
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\onnxocr\predict_system.py", line 4, in <module>
    import onnxocr.predict_det as predict_det
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\onnxocr\predict_det.py", line 3, in <module>
    from onnxocr.db_postprocess import DBPostProcess
  File "D:\GameTool\ZenlessZoneZero-OneDragon\src\onnxocr\db_postprocess.py", line 25, in <module>
    from shapely.geometry import Polygon
ModuleNotFoundError: No module named 'shapely'

**Comment by DoctorReid** [comment]
更新代码再安装依赖试试

**Comment by MurphyZX** [comment]
> 更新代码再依赖安装尝试

可以了
