### ISSUE TITLE
[问题反馈] [通用] 运行依赖安装失败

### ISSUE THREAD

**Issue by hzr12** [DoctorReid/ZenlessZoneZero-OneDragon#80]
### 问题描述

运行依赖安装失败

### 游戏截图

![image](https://github.com/user-attachments/assets/5269c557-7d70-4c07-b6fd-643f2dcc2026)

### 运行日志

[11:50:04.219] [all_install_card.py 58] [INFO]: 一键安装 开始下一个
[11:50:04.228] [git_service.py 238] [INFO]: 检测当前代码分支
[11:50:04.230] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\PortableGit\cmd\git.exe branch --show-current
[11:50:04.327] [python_service.py 157] [INFO]: 检测当前python版本
[11:50:04.333] [python_service.py 30] [INFO]: 开始安装 python
[11:50:04.335] [python_service.py 40] [INFO]: 开始解压 python-3.11.9-embed-amd64.zip
[11:50:04.630] [cmd_utils.py 49] [INFO]: main
[11:50:04.642] [git_service.py 166] [INFO]: 获取远程代码
[11:50:04.643] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\PortableGit\cmd\git.exe fetch origin main
[11:50:06.398] [python_service.py 45] [INFO]: 解压成功
[11:50:06.519] [python_service.py 184] [INFO]: 检测当前pip版本
[11:50:06.523] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\python\python.exe -m pip --version
[11:50:06.995] [cmd_utils.py 57] [ERROR]: F:\ZenlessZoneZeroOneDragon\.env\python\python.exe: No module named pip
[11:50:07.002] [python_service.py 78] [INFO]: 开始安装 pip
[11:50:07.007] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\python\python.exe F:\ZenlessZoneZeroOneDragon\.env\get-pip.py --index-url https://pypi.tuna.tsinghua.edu.cn/simple
[11:50:07.780] [cmd_utils.py 57] [ERROR]: From https://github.com/DoctorReid/ZenlessZoneZero-OneDragon
[11:50:07.787] [cmd_utils.py 57] [ERROR]: * branch            main       -> FETCH_HEAD
[11:50:07.794] [git_service.py 174] [ERROR]: 获取远程代码成功
[11:50:07.796] [git_service.py 260] [INFO]: 检测当前代码是否最新
[11:50:07.800] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\PortableGit\cmd\git.exe diff --name-only HEAD origin/main
[11:50:14.900] [cmd_utils.py 49] [INFO]: Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
[11:50:15.588] [cmd_utils.py 49] [INFO]: Collecting pip
[11:50:15.669] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d4/55/90db48d85f7689ec6f81c0db0622d704306c5284850383c090e6c7195a5c/pip-24.2-py3-none-any.whl (1.8 MB)
[11:50:16.241] [cmd_utils.py 49] [INFO]: Collecting setuptools
[11:50:16.326] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6e/ec/06715d912351edc453e37f93f3fc80dcffd5ca0e70386c87529aca296f05/setuptools-72.2.0-py3-none-any.whl (2.3 MB)
[11:50:16.739] [cmd_utils.py 49] [INFO]: Collecting wheel
[11:50:16.823] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl (67 kB)
[11:50:17.005] [cmd_utils.py 49] [INFO]: Installing collected packages: wheel, setuptools, pip
[11:51:00.713] [cmd_utils.py 49] [INFO]: Successfully installed pip-24.2 setuptools-72.2.0 wheel-0.44.0
[11:51:01.983] [cmd_utils.py 57] [ERROR]: WARNING: The script wheel.exe is installed in 'F:\ZenlessZoneZeroOneDragon\.env\python\Scripts' which is not on PATH.
[11:51:01.987] [cmd_utils.py 57] [ERROR]: Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[11:51:01.990] [cmd_utils.py 57] [ERROR]: WARNING: The scripts pip.exe, pip3.11.exe and pip3.exe are installed in 'F:\ZenlessZoneZeroOneDragon\.env\python\Scripts' which is not on PATH.
[11:51:01.991] [cmd_utils.py 57] [ERROR]: Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[11:51:01.993] [python_service.py 94] [INFO]: 安装pip成功
[11:51:01.994] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\python\python.exe -m pip install virtualenv --index-url https://pypi.tuna.tsinghua.edu.cn/simple
[11:51:06.089] [cmd_utils.py 49] [INFO]: Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
[11:51:06.535] [cmd_utils.py 49] [INFO]: Collecting virtualenv
[11:51:06.613] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/07/4d/410156100224c5e2f0011d435e477b57aed9576fc7fe137abcf14ec16e11/virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
[11:51:06.720] [cmd_utils.py 49] [INFO]: Collecting distlib<1,>=0.3.7 (from virtualenv)
[11:51:06.795] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/8e/41/9307e4f5f9976bc8b7fea0b66367734e8faf3ec84bc0d412d8cfabbb66cd/distlib-0.3.8-py2.py3-none-any.whl (468 kB)
[11:51:06.891] [cmd_utils.py 49] [INFO]: Collecting filelock<4,>=3.12.2 (from virtualenv)
[11:51:07.197] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ae/f0/48285f0262fe47103a4a45972ed2f9b93e4c80b8fd609fa98da78b2a5706/filelock-3.15.4-py3-none-any.whl (16 kB)
[11:51:07.200] [cmd_utils.py 49] [INFO]: Collecting platformdirs<5,>=3.9.1 (from virtualenv)
[11:51:07.211] [cmd_utils.py 49] [INFO]: Using cached https://pypi.tuna.tsinghua.edu.cn/packages/68/13/2aa1f0e1364feb2c9ef45302f387ac0bd81484e9c9a4c5688a322fbdfd08/platformdirs-4.2.2-py3-none-any.whl (18 kB)
[11:51:07.247] [cmd_utils.py 49] [INFO]: Installing collected packages: distlib, platformdirs, filelock, virtualenv
[11:51:14.982] [cmd_utils.py 49] [INFO]: Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
[11:51:15.950] [cmd_utils.py 57] [ERROR]: WARNING: The script virtualenv.exe is installed in 'F:\ZenlessZoneZeroOneDragon\.env\python\Scripts' which is not on PATH.
[11:51:15.956] [cmd_utils.py 57] [ERROR]: Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[11:51:15.958] [python_service.py 119] [INFO]: 安装virtualenv成功
[11:51:15.959] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\python\python.exe -m virtualenv F:\ZenlessZoneZeroOneDragon\.env\venv
[11:51:31.864] [cmd_utils.py 49] [INFO]: created virtual environment CPython3.11.9.final.0-64 in 14917ms
[11:51:31.869] [cmd_utils.py 49] [INFO]: creator CPython3Windows(dest=F:\ZenlessZoneZeroOneDragon\.env\venv, clear=False, no_vcs_ignore=False, global=False)
[11:51:31.870] [cmd_utils.py 49] [INFO]: seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Administraror\AppData\Local\pypa\virtualenv)
[11:51:31.871] [cmd_utils.py 49] [INFO]: added seed packages: pip==24.1, setuptools==70.1.0, wheel==0.43.0
[11:51:31.872] [cmd_utils.py 49] [INFO]: activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[11:51:31.937] [python_service.py 136] [INFO]: 创建虚拟环境成功
[11:51:32.042] [all_install_card.py 58] [INFO]: 一键安装 开始下一个
[11:51:32.052] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\venv\scripts\python.exe -m pip install --upgrade -r F:\ZenlessZoneZeroOneDragon\requirements-prod.txt
[11:51:32.054] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\venv\scripts\python.exe -c import sys; print(sys.prefix == sys.base_prefix)
[11:51:32.375] [cmd_utils.py 49] [INFO]: False
[11:51:32.385] [python_service.py 157] [INFO]: 检测当前python版本
[11:51:32.388] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\venv\scripts\python.exe --version
[11:51:32.480] [cmd_utils.py 49] [INFO]: Python 3.11.9
[11:51:36.518] [cmd_utils.py 57] [ERROR]: Traceback (most recent call last):
[11:51:36.523] [cmd_utils.py 57] [ERROR]: File "<frozen runpy>", line 198, in _run_module_as_main
[11:51:36.527] [cmd_utils.py 57] [ERROR]: File "<frozen runpy>", line 88, in _run_code
[11:51:36.528] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\__main__.py", line 24, in <module>
[11:51:36.529] [cmd_utils.py 57] [ERROR]: sys.exit(_main())
[11:51:36.531] [cmd_utils.py 57] [ERROR]: ^^^^^^^
[11:51:36.531] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main.py", line 65, in main
[11:51:36.532] [cmd_utils.py 57] [ERROR]: cmd_name, cmd_args = parse_command(args)
[11:51:36.533] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^
[11:51:36.534] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 79, in parse_command
[11:51:36.535] [cmd_utils.py 57] [ERROR]: general_options, args_else = parser.parse_args(args)
[11:51:36.536] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.537] [cmd_utils.py 57] [ERROR]: File "optparse.py", line 1371, in parse_args
[11:51:36.540] [cmd_utils.py 57] [ERROR]: values = self.get_default_values()
[11:51:36.550] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.554] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\parser.py", line 279, in get_default_values
[11:51:36.559] [cmd_utils.py 57] [ERROR]: self.config.load()
[11:51:36.571] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 124, in load
[11:51:36.581] [cmd_utils.py 57] [ERROR]: self._load_config_files()
[11:51:36.589] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 246, in _load_config_files
[11:51:36.594] [cmd_utils.py 57] [ERROR]: config_files = dict(self.iter_config_files())
[11:51:36.604] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.605] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 339, in iter_config_files
[11:51:36.610] [cmd_utils.py 57] [ERROR]: config_files = get_configuration_files()
[11:51:36.613] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.618] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 70, in get_configuration_files
[11:51:36.625] [cmd_utils.py 57] [ERROR]: os.path.join(path, CONFIG_BASENAME) for path in appdirs.site_config_dirs("pip")
[11:51:36.628] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.633] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 47, in site_config_dirs
[11:51:36.640] [cmd_utils.py 57] [ERROR]: dirval = _appdirs.site_config_dir(appname, appauthor=False, multipath=True)
[11:51:36.642] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.649] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 142, in site_config_dir
[11:51:36.653] [cmd_utils.py 57] [ERROR]: ).site_config_dir
[11:51:36.654] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^
[11:51:36.655] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 67, in site_config_dir
[11:51:36.656] [cmd_utils.py 57] [ERROR]: return self.site_data_dir
[11:51:36.658] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^
[11:51:36.658] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 56, in site_data_dir
[11:51:36.659] [cmd_utils.py 57] [ERROR]: path = os.path.normpath(get_win_folder("CSIDL_COMMON_APPDATA"))
[11:51:36.660] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.661] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 209, in get_win_folder_from_registry
[11:51:36.662] [cmd_utils.py 57] [ERROR]: directory, _ = winreg.QueryValueEx(key, shell_folder_name)
[11:51:36.662] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:36.668] [cmd_utils.py 57] [ERROR]: FileNotFoundError: [WinError 2] ϵͳҲָļ
[11:51:46.497] [cmd_utils.py 19] [INFO]: F:\ZenlessZoneZeroOneDragon\.env\venv\scripts\python.exe -m pip install --upgrade -r F:\ZenlessZoneZeroOneDragon\requirements-prod.txt
[11:51:48.472] [cmd_utils.py 57] [ERROR]: Traceback (most recent call last):
[11:51:48.479] [cmd_utils.py 57] [ERROR]: File "<frozen runpy>", line 198, in _run_module_as_main
[11:51:48.483] [cmd_utils.py 57] [ERROR]: File "<frozen runpy>", line 88, in _run_code
[11:51:48.491] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\__main__.py", line 24, in <module>
[11:51:48.492] [cmd_utils.py 57] [ERROR]: sys.exit(_main())
[11:51:48.493] [cmd_utils.py 57] [ERROR]: ^^^^^^^
[11:51:48.494] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main.py", line 65, in main
[11:51:48.495] [cmd_utils.py 57] [ERROR]: cmd_name, cmd_args = parse_command(args)
[11:51:48.496] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^
[11:51:48.497] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 79, in parse_command
[11:51:48.498] [cmd_utils.py 57] [ERROR]: general_options, args_else = parser.parse_args(args)
[11:51:48.502] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.507] [cmd_utils.py 57] [ERROR]: File "optparse.py", line 1371, in parse_args
[11:51:48.517] [cmd_utils.py 57] [ERROR]: values = self.get_default_values()
[11:51:48.529] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.533] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\cli\parser.py", line 279, in get_default_values
[11:51:48.537] [cmd_utils.py 57] [ERROR]: self.config.load()
[11:51:48.541] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 124, in load
[11:51:48.547] [cmd_utils.py 57] [ERROR]: self._load_config_files()
[11:51:48.554] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 246, in _load_config_files
[11:51:48.555] [cmd_utils.py 57] [ERROR]: config_files = dict(self.iter_config_files())
[11:51:48.556] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.557] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 339, in iter_config_files
[11:51:48.558] [cmd_utils.py 57] [ERROR]: config_files = get_configuration_files()
[11:51:48.559] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.561] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\configuration.py", line 70, in get_configuration_files
[11:51:48.562] [cmd_utils.py 57] [ERROR]: os.path.join(path, CONFIG_BASENAME) for path in appdirs.site_config_dirs("pip")
[11:51:48.567] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.571] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_internal\utils\appdirs.py", line 47, in site_config_dirs
[11:51:48.574] [cmd_utils.py 57] [ERROR]: dirval = _appdirs.site_config_dir(appname, appauthor=False, multipath=True)
[11:51:48.585] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.591] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 142, in site_config_dir
[11:51:48.597] [cmd_utils.py 57] [ERROR]: ).site_config_dir
[11:51:48.601] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^
[11:51:48.607] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 67, in site_config_dir
[11:51:48.612] [cmd_utils.py 57] [ERROR]: return self.site_data_dir
[11:51:48.614] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^
[11:51:48.615] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 56, in site_data_dir
[11:51:48.618] [cmd_utils.py 57] [ERROR]: path = os.path.normpath(get_win_folder("CSIDL_COMMON_APPDATA"))
[11:51:48.619] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.620] [cmd_utils.py 57] [ERROR]: File "F:\ZenlessZoneZeroOneDragon\.env\venv\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 209, in get_win_folder_from_registry
[11:51:48.621] [cmd_utils.py 57] [ERROR]: directory, _ = winreg.QueryValueEx(key, shell_folder_name)
[11:51:48.623] [cmd_utils.py 57] [ERROR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11:51:48.633] [cmd_utils.py 57] [ERROR]: FileNotFoundError: [WinError 2] ϵͳҲָļ

**Comment by hzr12** [comment]
[log.txt](https://github.com/user-attachments/files/16621686/log.txt)

**Comment by DoctorReid** [comment]
可以参考 [常见问题](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by hzr12** [comment]
但我其他的python还需要用怎么办

**Comment by DoctorReid** [comment]
那就自己创建环境，安装器里选自己的环境

**Comment by hzr12** [comment]
就是用anaconda创建一个env？

**Comment by hzr12** [comment]
我觉得可以为了这个项目下载一个python单独为这个程序用
